{% set name = "waybackpack" %}
{% set version = "0.3.7" %}
{% set compress_type = "tar.gz" %}
{% set hash = "c120b68f7bdd8f14626c2363f7422fe2938866d31380fcd2ad43e89e25d6a7a6" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  sha256: {{ hash }}

build:
  noarch: python
  entry_points:
    - waybackpack = waybackpack.cli:main
  number: {{ build }}
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - requests

test:
  imports:
    - waybackpack

  commands:
    - waybackpack --help

about:
  home: https://github.com/jsvine/waybackpack
  # No MANIFEST.in - see https://github.com/jsvine/waybackpack/pull/25
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Command-line tool that lets you download the entire Wayback Machine archive for a given URL.
  dev_url: https://github.com/jsvine/waybackpack
  doc_url: https://github.com/jsvine/waybackpack

extra:
  recipe-maintainers:
    - pmlandwehr
