{% set name = "waybackpack" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4324973a9681de0cd9331ba998bbbb404864b6cdfa0ee8520ab7beb3a1c88c9a

build:
  noarch: python
  entry_points:
    - waybackpack = waybackpack.cli:main
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools

  run:
    - python >={{ python_min }}
    - requests

test:
  imports:
    - waybackpack

  commands:
    - waybackpack --help
    - pip check

  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jsvine/waybackpack
  # No MANIFEST.in - see https://github.com/jsvine/waybackpack/pull/25
  license_file: {{ RECIPE_DIR }}/LICENSE.txt
  license: MIT
  license_family: MIT
  summary: Command-line tool that lets you download the entire Wayback Machine archive for a given URL.
  dev_url: https://github.com/jsvine/waybackpack
  doc_url: https://github.com/jsvine/waybackpack

extra:
  recipe-maintainers:
    - pmlandwehr
    - jan-janssen
