travis:
  secure:
    BINSTAR_TOKEN: mohl4wUu9232LtztDyV8Cyes9kgljoN5UxV0d6CqU4MjBjTqNtPQdp2z+qiP411nBUG7v3axffPdydpiSrMo99iTbaVMFyZs1dtZMNs0wlmZ1GfNV4gUt0vcaJ+3ck6jSBznhLuo36qLWED0GePcveXLkRRb+epWYQGrywMqqns9mxF+IYmCDwZI2EzuOzavkX+WO7xNR3pZhsprHllFNd7iZJxCRbcwmj0rcRKMCSeNsk/yECeRzjTfo1abSP3JASQYYNYqez/yPT5CMtBmHdYf5ciQ+2VX5Pbq9iCDUcS1CewEF6UlJMevVsHpBssUc85pDa909AShNqMCOAmzFr0df4bBHneD+OPQHQGOifJ2Z/Cgz5IkEl9a+pJQEU0LU89TL+hd20A8SFPvvKav2dJeyg/FlDTIKuEZFP55jc25FzWN1POyu7BVCBEJJQ4e9uAD6ssg9CYl43e0nLYC8hwoQpZFjE/8BfuPSOscgMtn13LiwugbZwfoTt9/Vv6HhJKhvYhCvkID9xFvWocUAZSHDtrfvVV6spFd9C7lDhWAFWqZ1AANRUzPBczFW9Mz3JPFdmFDfLxr/JO9YqpfwXt++yyIZQO0F7q9EpaP2Nei5TAwBFgG+nqFstQXiJKyb8rLClfVOQWHmFK8b09dsMWJwEReIb6mbLDxboaWiOE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
