travis:
  secure:
    BINSTAR_TOKEN: jbSDSwQRXT2nDeyxxfg5sTOhtR3Km/YXjthEoVySBOVrGLnnrmjWJhRKmawzaHktWWy4eKhFk1SXKL2eRM6r5hxEt7hpwnbWPdVkj/fzf++gJgd5nFuBmTAh1anc+MXd6mZkpoUJ8i0un1ctDOHSaITsmkrkjF6EOP+1wuHOCE/h3PiVyA8jmzn4QDSaJ3DTG6pxa6JZ+rrTOxiLBpJdO+2Y7/vdKUmulLBCsIScjT1AiS+VMWVf1IH7cT6xF70lbC7FevBGj2xGN8UQAGhOgQw5acckEM6g//1Dq3tuyi81weaqRz63H4068WIaeShsdhNaXo6M8NWlOhBlZYKzYZiPGO5K7u/RweUAKxjsYXqr4uDQ9yfQiMbA1FiZPVu/AU82XCv8+2euYI5vuAze/tAXGPO0Mn1X7+wjKHFOiL3AcUoM3jckzSk4oW//3jo1Sw6l/AV9Wy1UIkQ8HYNTPwufvuYiPozY/TYr4ILynFqpz4YY8qqpG3+1J/MboxxNe1DQh9hMimbN/QiBeLBWurcrlMDeJ+C6ZkRIdb5GWF8/1ER3TpAzP4cPl+TMQq+Nv0REiefS4o1idVqVGXIFfek5LHkMzHH3PqQl2+anbAQod4gKMHYC0tATID4RKwtmYa1tz5jsuKX5YAVoOsNq8b01kHzDslDrZxHgHqoT43I=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
